on:
  issues:
    types:
      - opened
  discussion:
    types: [created]

  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change README.md
        run: |
          time=$(date +%F -d "${{github.event.issue.updated_at}}")
          echo "- [${{ github.event.issue.title}}](${{github.event.issue.html_url}}) $time" >> README.md
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git add README.md
          git commit -m "(Automated) Update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

  ##################################################
  new-discussion:
    runs-on: ubuntu-latest
    needs: issue-manager
    steps:
      - run: |
          gh api -i graphql -f query='
            mutation {
              createDiscussion(
                input: {repositoryId: "R_kgDOG8xRxA", categoryId: "DIC_kwDOG8xRxM4CN9Zd",
                  title: "${{github.event.issue.title}}", body: "具体内容请看：${{github.event.issue.html_url}}"
                }
              )
              {
                discussion {
                  id
                  number
                  title
                }
              }
            }
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  issue-reply:
    runs-on: ubuntu-latest
    needs: new-discussion
    steps:
      - run: gh issue comment $ISSUE --body "内容已经同步到：${{github.event.discussion.html_url}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
