name: airdrop solana for devnet

on:
  schedule:
    - cron: "30 0,12 * * *"
  workflow_dispatch:

jobs:
  airdrop-some-sol:
    runs-on: ubuntu-latest
    steps:
      - name: install solana
        uses: metaplex-foundation/actions/install-solana@v1
        with:
          version: stable
          cache: true

      - name: airdrop solana
        run: |
          solana -V
          echo ${{ secrets.SOLANA_PRIV_KEY }} > ~/.config/solana/id.json
          solana config set --url https://api.devnet.solana.com
          solana balance
          solana airdrop 5 2>&1
          solana balance
