name: airdrop solana for devnet

on:
  schedule:
    - cron: "30 0,12 * * *"
  workflow_dispatch:

jobs:
  airdrop-some-sol:
    runs-on: ubuntu-latest
    steps:
      - name: cache solana
        id: cache
        if: inputs.cache == 'true'
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.local/share/solana/install/active_release/
            /home/codespace/.local/share/solana/install/active_release/
          key: ${{ runner.os }}-solana

      - name: install solana
        if: inputs.cache != 'true' || steps.cache.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          export PATH="/home/codespace/.local/share/solana/install/active_release/bin:$PATH"
          solana -V

      - name: airdrop solana
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          export PATH="/home/codespace/.local/share/solana/install/active_release/bin:$PATH"

          solana -V
          echo ${{ secrets.SOLANA_PRIV_KEY }} > ~/.config/solana/id.json
          solana config set --url https://api.devnet.solana.com
          solana balance
          solana airdrop 5 2>&1
          solana balance

#  https://github.com/metaplex-foundation/actions/tree/main/install-solana
